services:
  soundtouch-service:
    image: ghcr.io/gesellix/bose-soundtouch:${SOUNDTOUCH_VERSION:-latest}
    container_name: soundtouch-service
    # ports:
      # - "8000:8000"
    environment:
      - PORT=8000
      - DATA_DIR=/app/data
      - LOG_PROXY_BODY=false
      - REDACT_PROXY_LOGS=true
      - RECORD_INTERACTIONS=true
      - DISCOVERY_INTERVAL=5m
    volumes:
      - ./data:/app/data
    networks:
      - frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.soundtouch-http.rule=Host("bose.home.vdbossche.info")
      - traefik.http.routers.soundtouch-http.entrypoints=web
      - traefik.docker.network=frontend # This makes sure traefik uses the right docker network 
      - traefik.http.routers.soundtouch-http.service=soundtouch-http-svc
      - traefik.http.services.soundtouch-http-svc.loadbalancer.server.port=8000

networks:
  frontend:
    external: true