apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptimekuma
  namespace: uptimekuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: "2.24.0"
      sourceRef:
        kind: HelmRepository
        name: uptimekuma
        namespace: flux-system

  values:
    persistence:
      enabled: true
      size: 5Gi

    ingress:
      enabled: true
      className: traefik

    annotations:
      cert-manager.io/cluster-issuer: cloudflare

    hosts:
      - host: status.cluster.vdbhome.ovh
        paths:
          - path: /
            pathType: Prefix
      - host: status.vdbhome.ovh
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: uptime-kuma-tls
        hosts:
          - status.cluster.vdbhome.ovh
          - status.vdbhome.ovh
