---
services:
  handbrake:
    image: lscr.io/linuxserver/handbrake:latest
    container_name: handbrake
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./watch:/watch
      - ./output:/output
      - /etc/localtime:/etc/localtime:ro
    labels:
    - traefik.enable=true
    - traefik.docker.network=frontend
    - traefik.http.routers.handbrake-https.tls=true
    - traefik.http.routers.handbrake-https.tls.certresolver=cloudflare
    - traefik.http.routers.handbrake-https.rule=Host("handbrake.prod.vdbhome.ovh")
    - traefik.http.routers.handbrake-https.entrypoints=websecure
    - traefik.http.routers.handbrake-https.service=handbrake-https-svc
    - traefik.http.services.handbrake-https-svc.loadbalancer.server.port=3000
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true