apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:1o/dNK06Xx4viK9/Z8oT1KQFwgwydwseJlxhWE4ll/RhMGUq1znHZw==,iv:dw96BQ8RzgXNAe/bJ+bjvZoQOqUwha2R5wYveyHAwBI=,tag:YTKPzCJS2no3ZJHV7RGGLg==,type:str]
sops:
    age:
        - recipient: age1gj7qqmxejaldhaj9k224x8tx88rny0779vk4jrg07lt53yfwwq0qsc7e0a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QVJaREg0NG5XVFE5SDhr
            SWZaYUFYSUdBRStjclpRUFQ0MldjdjRpN25FCkcyd0FRMkQxMSswTnl3Z21xRVNv
            UUIyQU5nWTFVbjkwWWU0Uk43UWd2eUUKLS0tIFVZMHI4UHRCbExITDZodmVYZ1ZO
            aEw2WXdTRXh4Tjk5bjVqYUEvWlgva1kKEEo2q2slpzl5LHMM0Y3VyjneO9LQzuJi
            CXIAUy+LmGUu4wFmLeacHLaH8tXtEohcPZQDTktY/0aMgXLh8LbXrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T20:05:30Z"
    mac: ENC[AES256_GCM,data:+t+EUWvhjPke9LlRe/+KgS7R0bKc7bFiEd06lX9loQn8bwff0SdVWw+sVqN+GYuIDjZKFgLZRHJ2XD0r54cdB2lguxqOWEYmbdHDN0k4Mhp7e/U+Mvc9pZJZhxL7oUXcGy0xHRS5JcE8Sdkw25SVjjYlBKpLZqYBxasdqBT3btY=,iv:RgwkRRQPvdaVr5osjHKyJo0RKbyhNh2XbMtYfv4zk0M=,tag:dVLI7XadoP/1qHEUygsZEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
