apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system

  install:
    crds: Create
  upgrade:
    crds: Create

  values:
    extraObjects:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: cloudflare
        spec:
          acme:
            email: you@example.com
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: cloudflare-account-key
            solvers:
              - dns01:
                  cloudflare:
                    apiTokenSecretRef:
                      name: cloudflare-api-token
                      key: api-token
