apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 10m
  path: ./HA/k3s/clusters/home/infrastructure/kube-vip
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
