services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: woutvdb.be
    # Ensure it only listens on the Netbird IP to keep it off your local home LAN
    ports:
      - "100.66.16.193:25:25"   # SMTP
      - "100.66.16.193:587:587" # Submission
      - "100.66.16.193:993:993" # IMAPS
    environment:
      - OVERTAKE_IP=193.190.253.116 # Tells DMS your public identity
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1 # Save ~1GB RAM by keeping this off
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/mail.woutvdb.be_ecc/fullchain.cer
      - SSL_KEY_PATH=/etc/letsencrypt/mail.woutvdb.be_ecc/mail.woutvdb.be.key    
    volumes:
      - ./certs:/etc/letsencrypt:ro
      - ./mail-data:/var/mail
      - ./mail-state:/var/mail-state
      - ./mail-logs:/var/log/mail
      - ./config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    restart: always

  acme-sh:
    image: neilpang/acme.sh
    container_name: acme-sh
    restart: always
    command: daemon
    volumes:
      - ./certs:/acme.sh
    environment:
      # Replace with your specific DNS provider keys
      - CF_Token=${CF_Token}
      - CF_Account_ID=${CF_Account_ID}