---
services:
  netbox:
    image: docker.io/netboxcommunity/netbox:v4.5-4.0.2
    restart: unless-stopped
    environment:
      - ALLOWED_HOSTS=netbox.prod.vdbhome.ovh
      - DB_HOST=postgres
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_ENGINE=django.db.backends.postgresql
      - REDIS_HOST=netbox_redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CACHE_HOST=netbox_redis-cache
      - REDIS_CACHE_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${NETBOX_SECRET_KEY}
    networks:
      frontend:
      netbox_backend:
      backend:
    volumes:
      - netbox_media:/opt/netbox/netbox/media
      - netbox_reports:/opt/netbox/netbox/reports
      - netbox_scripts:/opt/netbox/netbox/scripts
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.netbox_web.loadBalancer.server.port=8080
      - traefik.http.routers.netbox_http.service=netbox_web
      - traefik.http.routers.netbox_http.rule=Host(`netbox.prod.vdbhome.ovh`)
      - traefik.http.routers.netbox_http.entrypoints=web
      - traefik.http.routers.netbox_https.service=netbox_web
      - traefik.http.routers.netbox_https.rule=Host(`netbox.prod.vdbhome.ovh`)
      - traefik.http.routers.netbox_https.entrypoints=websecure
      - traefik.http.routers.netbox_https.tls=true
      - traefik.http.routers.netbox_https.tls.certresolver=cloudflare
    depends_on:
      - netbox_redis
      - netbox_redis-cache

  netbox_worker:
    image: docker.io/netboxcommunity/netbox:v4.5-4.0.2
    restart: unless-stopped
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    environment:
      - DB_HOST=postgres
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_ENGINE=django.db.backends.postgresql
      - REDIS_HOST=netbox_redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CACHE_HOST=netbox_redis-cache
      - REDIS_CACHE_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${NETBOX_SECRET_KEY}
    networks:
      netbox_backend:
    volumes:
      - netbox_media:/opt/netbox/netbox/media
      - netbox_reports:/opt/netbox/netbox/reports
      - netbox_scripts:/opt/netbox/netbox/scripts
    depends_on:
      - netbox
      - netbox_redis
      - netbox_redis-cache

  netbox_redis:
    image: docker.io/library/redis:8.6.0-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      netbox_backend:
    volumes:
      - netbox_redis:/data

  netbox_redis-cache:
    image: docker.io/library/redis:8.6.0-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      netbox_backend:
    volumes:
      - netbox_redis-cache:/data

networks:
  netbox_backend:
    driver: bridge
  frontend:
    external: true
  backend:
    external: true

volumes:
  netbox_redis:
    driver: local
  netbox_redis-cache:
    driver: local
  netbox_media:
    driver: local
  netbox_reports:
    driver: local
  netbox_scripts:
    driver: local
