#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${NEXTCLOUD_DB};
  CREATE USER ${NEXTCLOUD_USER} WITH ENCRYPTED PASSWORD '${NEXTCLOUD_PASSWORD}';
  ALTER DATABASE ${NEXTCLOUD_DB} OWNER TO ${NEXTCLOUD_USER};

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${IMMICH_DB};
  CREATE USER ${IMMICH_USER} WITH ENCRYPTED PASSWORD '${IMMICH_PASSWORD}';
  ALTER DATABASE ${IMMICH_DB} OWNER TO ${IMMICH_USER};

EOSQL
