apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-vip
      version: "v1.0.4"
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system

  values:
    env:
      vip_interface: wt0
      vip_address: 100.66.55.44
      cp_enable: "true"
