#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${AUTHENTIK_DB};
  CREATE USER ${AUTHENTIK_USER} WITH ENCRYPTED PASSWORD '${AUTHENTIK_PASSWORD}';
  ALTER DATABASE ${AUTHENTIK_DB} OWNER TO ${AUTHENTIK_USER};

  CREATE DATABASE ${VAULTWARDEN_DB};
  CREATE USER ${VAULTWARDEN_USER} WITH ENCRYPTED PASSWORD '${VAULTWARDEN_PASSWORD}';
  ALTER DATABASE ${VAULTWARDEN_DB} OWNER TO ${VAULTWARDEN_USER};
EOSQL
